# Generated by Django 5.2.4 on 2025-07-28 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('week_count', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.campus')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.semester')),
            ],
            options={
                'unique_together': {('course', 'semester', 'weekday', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('course_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.courseslot')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], default='APPROVED', max_length=16)),
                ('paid_status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID')], default='PAID', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.semester')),
                ('sub_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.subgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('LATE', 'LATE')], default='PRESENT', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('course_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.courseslot')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.enrollment')),
                ('sub_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.subgroup')),
            ],
            options={
                'unique_together': {('enrollment', 'course_slot', 'week_no', 'sub_group')},
            },
        ),
    ]
