# Generated by Django 5.2.4 on 2025-07-28 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.courseslot'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='paid_status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID')], default='UNPAID', max_length=16),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=16),
        ),
    ]
