# Generated by Django 5.2.4 on 2025-07-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_classnotice_learningresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnotice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classnotice',
            name='order_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
