# Generated by Django 5.2.4 on 2025-07-31 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_classnotice_is_active_classnotice_order_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classnotice',
            options={'ordering': ('-is_pinned', '-order_no', '-created_at')},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PARENT', 'Parent'), ('ASSISTANT', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.enrollment')),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.subgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantComment',
            fields=[
            ],
            options={
                'verbose_name': 'Assistant Comment',
                'verbose_name_plural': 'Assistant Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.comment',),
        ),
        migrations.CreateModel(
            name='ParentComment',
            fields=[
            ],
            options={
                'verbose_name': 'Parent Comment',
                'verbose_name_plural': 'Parent Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.comment',),
        ),
    ]
