# Generated by Django 5.2.4 on 2025-08-05 02:11

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_classnotice_options_comment_assistantcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='learningresource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='learningresource',
            name='video_url',
        ),
        migrations.CreateModel(
            name='LearningResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', 'Video URL'), ('file', 'Attachment'), ('image', 'Image'), ('link', 'External link')], max_length=10)),
                ('video_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=portal.models.lr_upload_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=portal.models.lr_upload_path)),
                ('ext_url', models.URLField(blank=True, verbose_name='External URL')),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.learningresource')),
            ],
            options={
                'ordering': ('order_no', 'id'),
            },
        ),
    ]
