# Generated by Django 5.2.4 on 2025-08-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_learningresource_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresourceitem',
            name='order_no',
            field=models.PositiveIntegerField(blank=True, help_text='留空则按ID/创建时间倒序', null=True, verbose_name='Sort No.'),
        ),
    ]
