# Generated by Django 5.2.4 on 2025-08-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_learningresourceitem_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningresourceitem',
            old_name='resource',
            new_name='learning_resource',
        ),
        migrations.AlterField(
            model_name='learningresourceitem',
            name='ext_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningresourceitem',
            name='order_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learningresourceitem',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'Video URL'), ('FILE', 'Attachment'), ('IMAGE', 'Image'), ('LINK', 'External link')], max_length=10),
        ),
    ]
