# Generated by Django 5.2.4 on 2025-08-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Waiting for approve'), ('APPROVED', 'Approved'), ('REJECTED', 'Register rejected')], default='PENDING', max_length=8),
        ),
    ]
